name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run linter
        run: bun run lint

      - name: Run tests with coverage
        run: bun run test:ci

      - name: Build application
        run: bun run build
        env:
          # Provide dummy environment variables for build
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY || 'dummy-key' }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY || 'dummy-key' }}
          NEO4J_URI: ${{ secrets.NEO4J_URI || 'bolt://localhost:7687' }}
          NEO4J_USERNAME: ${{ secrets.NEO4J_USERNAME || 'neo4j' }}
          NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD || 'dummy-password' }}
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY || 'dummy-key' }}
          POSTHOG_HOST: ${{ secrets.POSTHOG_HOST || 'https://eu.i.posthog.com' }}
          APP_DOMAIN: ${{ secrets.APP_DOMAIN || 'http://localhost:3000' }}


      - name: Upload test results and coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-coverage-results
          path: |
            test-results.xml
            coverage/
          retention-days: 30