name: Run Knowledge Base Graph Update

on:
  push:
    branches:
      - main

jobs:
  update-graph:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./knowledge-base
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13' # Assuming Python 3.11, adjust if needed

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        shell: bash

      - name: Install dependencies
        run: uv pip install .

      - name: Run graph update
        env:
          NEO4J_URI: ${{ secrets.NEO4J_URI }}
          NEO4J_USERNAME: ${{ secrets.NEO4J_USERNAME }}
          NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
        run: uv run python main.py --actions graph 